# Task 6 Data science Internship with innomatics Research Labs

Assignment Name

Task - 6 (Numpy - Both for Basic and Adv User) 


Arrays

In [1]:
import numpy

def arrays(arr):
    a=numpy.array(arr, float)
    return a[::-1]
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


Shape and Reshape



In [2]:
import numpy as np
a= (input().split())
b=np.array(a, dtype=int)
c=b.reshape(3,3)
print(c)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transpose and Flatten



In [3]:
import numpy as np
nm=input().split()
n,m=int(nm[0]), int(nm[1])
array=[input().split() for i in range(n)]
result=np.array(array, dtype=int)
print(np.transpose(result))
print(result.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


Concatenate

In [4]:
import numpy as np
abc=input().split()
a,b,c=int(abc[0]),int(abc[1]),int(abc[2])
arrays=[input().split() for i in range(a+b)]
print(np.array(arrays,dtype=int))

4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


Zeros and Ones



In [5]:
import numpy as np
a=tuple(map(int, input().split()))
print(np.zeros(a,dtype =int))
print(np.ones(a,dtype =int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Eye and Identity



In [6]:
import numpy as np
n,m=map(int,input().split())
result=str(np.eye(n,m))
print(result.replace("0", " 0").replace("1", " 1"))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Array Mathematics

In [10]:
import numpy as np
N,M=map(int,input().split())
A=np.array([input().split() for i in range(N)],dtype=int)
B=np.array([input().split() for i in range(N)],dtype=int)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Floor, Ceil and Rint

In [9]:
import numpy as np
np.set_printoptions(sign=" ")
a=np.array(input().split(), dtype=float)
f=np.floor(a)
c=np.ceil(a)
r=np.rint(a)
print(f)
print(c)
print(r)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Sum and Prod



In [11]:
import numpy as np
n,m=map(int,input().split())
l=[]
for i in range(n):
    l1=list(map(int,input().split()))
    l.append(l1)
array=np.array(l)
s=np.sum(array,axis=0)
p=np.prod(s,axis=0)
print(p)

2 2
1 2
3 4
24


Min and Max

In [12]:
import numpy as np
n,m=list(map(int, input().split()))
array=np.array([input().split() for i in range(n)],dtype=int)
min=np.min(array,axis=1)
max=np.max(min)
print(max)

4 2
2 5
3 7
1 3
4 0
3


Mean, Var, and Std

In [13]:
import numpy as np
n,m=list(map(int,input().split()))
array=np.array([input().split() for i in range(n)],dtype=int)
print(np.mean(array,axis=1))
print(np.var(array,axis=0))
std=np.std(array,axis=None)
print(std.round(11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


Dot and Cross



In [16]:
import numpy as np
N=int(input())
A=np.array([input().split() for i in range(N)],dtype=int)
B=np.array([input().split() for i in range(N)],dtype=int)
print(A.dot(B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


Inner and Outer

In [15]:
import numpy as np
A=np.array(input().split(),dtype=int)
B=np.array(input().split(),dtype=int)
print(np.inner(A,B))
print(np.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


Polynomials



In [17]:
import numpy as np
array=np.array(input().split(),dtype=float)
print(np.polyval(array,int(input())))

1.1 2 3
0
3.0


Linear Algebra

In [19]:
import numpy as np
N=int(input())
A=np.array([input().split() for i in range(N)],dtype=float)
print(np.linalg.det(A).round(2))

2
1.1 1.1
1.1 1.1
0.0
